import React, { createContext, useContext, useState } from "react";

export type Language = "English" | "Hindi" | "Bengali" | "Marathi" | "Tamil" | "Telugu" | "Gujarati" | "Kannada";

export const translations = {
  English: {
    dashboard: "Dashboard",
    workers: "Find Workers",
    jobs: "Jobs & Booking",
    wallet: "Wallet",
    mediator: "Mediator Roster",
    admin: "Admin Console",
    logout: "Logout",
    welcome: "Welcome back",
    topup: "Top Up Wallet",
    postJob: "Post a Job",
    findWorkers: "Find Nearest Workers",
    activeBookings: "Active Bookings",
    walletBalance: "Wallet Balance",
    verifiedWorkers: "Verified Workers",
    language: "Language",
    otpLogin: "OTP Login Demo",
    verifyOtp: "Verify OTP & Enter",
    phonePlaceholder: "Enter 10-digit mobile number",
    otpPlaceholder: "Enter 6-digit OTP (123456)",
    availableRoster: "Managed Roster List",
    addIvrWorker: "Add IVR Worker",
    disputesQueue: "Moderation Queue",
    resolveAlert: "Resolve Dispute Alert",
    resetDemo: "Reset Demo",
    radiusText: "Within radius",
    searchPlaceholder: "Search by worker name or skill...",
    allSkills: "All Skills",
    onlineOnly: "Online Only",
    allWorkers: "All Workers",
    bookEscrow: "Book with Escrow",
    insufficientBalance: "Insufficient wallet balance! Please recharge first.",
    ledgerTitle: "Immutable Transaction Ledger",
    platformCommissionText: "5% platform commission deducted only on job completion",
    commissionSaved: "Middlemen Costs Saved"
  },
  Hindi: {
    dashboard: "डैशबोर्ड",
    workers: "मजदूर खोजें",
    jobs: "काम और बुकिंग",
    wallet: "वॉलेट",
    mediator: "ठेकेदार सूची",
    admin: "एडमिन कंसोल",
    logout: "लॉगआउट",
    welcome: "आपका स्वागत है",
    topup: "वॉलेट रिचार्ज",
    postJob: "काम पोस्ट करें",
    findWorkers: "निकटतम मजदूर",
    activeBookings: "सक्रिय बुकिंग",
    walletBalance: "वॉलेट बैलेंस",
    verifiedWorkers: "सत्यापित मजदूर",
    language: "भाषा",
    otpLogin: "ओटीपी लॉगिन डेमो",
    verifyOtp: "ओटीपी सत्यापित करें",
    phonePlaceholder: "10-अंकीय मोबाइल नंबर दर्ज करें",
    otpPlaceholder: "6-अंकीय ओटीपी दर्ज करें (123456)",
    availableRoster: "प्रबंधित ठेका सूची",
    addIvrWorker: "आईवीआर मजदूर जोड़ें",
    disputesQueue: "प्रशासनिक समीक्षा",
    resolveAlert: "विवाद अलर्ट सुलझाएं",
    resetDemo: "डेमो रीसेट",
    radiusText: "त्रिज्या के भीतर",
    searchPlaceholder: "मजदूर का नाम या कौशल खोजें...",
    allSkills: "सभी कौशल",
    onlineOnly: "केवल ऑनलाइन",
    allWorkers: "सभी मजदूर",
    bookEscrow: "एस्क्रो से बुक करें",
    insufficientBalance: "वॉलेट बैलेंस कम है! कृपया पहले रीचार्ज करें।",
    ledgerTitle: "अपरिवर्तनीय लेनदेन बही",
    platformCommissionText: "काम पूरा होने पर केवल 5% प्लेटफ़ॉर्म कमीशन काटा जाता है",
    commissionSaved: "बिचौलिया लागत बचत"
  },
  Bengali: {
    dashboard: "ড্যাশবোর্ড",
    workers: "কর্মী খুঁজুন",
    jobs: "কাজ ও বুকিং",
    wallet: "ওয়ালেট",
    mediator: "মিডিয়েটর রোস্টার",
    admin: "অ্যাডমিন প্যানেল",
    logout: "লগ আউট",
    welcome: "স্বাগতম",
    topup: "ওয়ালেট রিচার্জ",
    postJob: "কাজ পোস্ট করুন",
    findWorkers: "নিকটবর্তী কর্মী",
    activeBookings: "চলতি বুকিং",
    walletBalance: "ওয়ালেট ব্যালেন্স",
    verifiedWorkers: "যাচাইকৃত কর্মী",
    language: "ভাষা",
    otpLogin: "ওটিপি লগইন ডেমো",
    verifyOtp: "ওটিপি যাচাই করুন",
    phonePlaceholder: "১০ ডিজিটের মোবাইল নম্বর",
    otpPlaceholder: "৬ ডিজিটের ওটিপি (123456)",
    availableRoster: "পরিচালিত কর্মী তালিকা",
    addIvrWorker: "আইভিআর কর্মী যোগ করুন",
    disputesQueue: "অ্যাডমিন রিভিউ কিউ",
    resolveAlert: "অ্যালার্ট সমাধান করুন",
    resetDemo: "ডেমো রিসেট",
    radiusText: "দূরত্ব ব্যাসার্ধ",
    searchPlaceholder: "নাম বা স্কিল খুঁজুন...",
    allSkills: "সব স্কিল",
    onlineOnly: "অনলাইন কর্মী",
    allWorkers: "সমস্ত কর্মী",
    bookEscrow: "এসক্রো বুকিং",
    insufficientBalance: "ওয়ালেট ব্যালেন্স অপর্যাপ্ত! রিচার্জ করুন।",
    ledgerTitle: "লেনদেন লেজার খাতা",
    platformCommissionText: "কাজ শেষ হলে মাত্র ৫% কমিশন কাটা হবে",
    commissionSaved: "দালাল খরচ সাশ্রয়"
  },
  Marathi: {
    dashboard: "डॅशबोर्ड",
    workers: "कामगार शोधा",
    jobs: "कामे आणि बुकिंग",
    wallet: "वॉलेट",
    mediator: "मध्यस्थ रोस्टर",
    admin: "अॅडमिन कंसोल",
    logout: "लॉगआउट",
    welcome: "स्वागत आहे",
    topup: "वॉलेट टॉप अप",
    postJob: "काम पोस्ट करा",
    findWorkers: "जवळचे कामगार",
    activeBookings: "सक्रिय बुकिंग",
    walletBalance: "वॉलेट शिल्लक",
    verifiedWorkers: "सत्यापित कामगार",
    language: "भाषा",
    otpLogin: "ओटीपी लॉगिन डेमो",
    verifyOtp: "ओटीपी सत्यापित करा",
    phonePlaceholder: "१०-अंकी मोबाईल नंबर टाका",
    otpPlaceholder: "६-अंकी ओटीपी टाका (123456)",
    availableRoster: "प्रबंधित कामगार यादी",
    addIvrWorker: "आयव्हीआर कामगार जोडा",
    disputesQueue: "प्रशासकीय पुनरावलोकन",
    resolveAlert: "वाद निवारण करा",
    resetDemo: "डेमो रीसेट",
    radiusText: "त्रिज्येच्या आत",
    searchPlaceholder: "नाव किंवा कौशल्य शोधा...",
    allSkills: "सर्व कौशल्ये",
    onlineOnly: "फक्त ऑनलाईन",
    allWorkers: "सर्व कामगार",
    bookEscrow: "एस्क्रोसह बुक करा",
    insufficientBalance: "वॉलेट शिल्लक अपुरी आहे! कृपया आधी रिचार्ज करा.",
    ledgerTitle: "अपरिवर्तनीय व्यवहार वही",
    platformCommissionText: "काम पूर्ण झाल्यावरच ५% कमिशन कापले जाईल",
    commissionSaved: "मध्यस्थांचा खर्च वाचला"
  },
  Tamil: {
    dashboard: "டாஷ்போர்டு",
    workers: "தொழிலாளர்கள்",
    jobs: "வேலைகள்",
    wallet: "பணப்பை",
    mediator: "மத்தியஸ்தர் பட்டியல்",
    admin: "நிர்வாக மையம்",
    logout: "வெளியேறு",
    welcome: "நல்வரவு",
    topup: "பணப்பை ஏற்றுக",
    postJob: "வேலை இடுகையிடு",
    findWorkers: "அருகிலுள்ள தொழிலாளர்கள்",
    activeBookings: "நடப்பு பதிவுகள்",
    walletBalance: "இருப்பு தொகை",
    verifiedWorkers: "சரிபார்க்கப்பட்டவர்கள்",
    language: "மொழி",
    otpLogin: "உள்நுழைவு",
    verifyOtp: "சரிபார்க்கவும்",
    phonePlaceholder: "10-இலக்க எண்",
    otpPlaceholder: "6-இலக்க கடவுச்சொல் (123456)",
    availableRoster: "பராமரிப்பு தொழிலாளர்கள்",
    addIvrWorker: "ஐவிஆர் சேர்க்க",
    disputesQueue: "நிர்வாக சரிபார்ப்பு",
    resolveAlert: "தீர்வு காண்க",
    resetDemo: "மீட்டமைக்க",
    radiusText: "சுற்றளவுக்குள்",
    searchPlaceholder: "தொழில் தேடுக...",
    allSkills: "அனைத்து தொழில்கள்",
    onlineOnly: "ஆன்லைன் மட்டும்",
    allWorkers: "அனைத்து தொழிலாளர்கள்",
    bookEscrow: "எஸ்க்ரோ முன்பதிவு",
    insufficientBalance: "இருப்பு போதுமானதாக இல்லை! பணம் சேர்க்கவும்.",
    ledgerTitle: "பரிவர்த்தனை குறிப்பேடு",
    platformCommissionText: "வேலை முடிந்ததும் 5% கட்டணம் கழிக்கப்படும்",
    commissionSaved: "தரகர் இல்லா சேமிப்பு"
  },
  Telugu: {
    dashboard: "డాష్ బోర్డ్",
    workers: "కార్మికులు",
    jobs: "పనులు",
    wallet: "వాలెట్",
    mediator: "మధ్యవర్తి రోస్టర్",
    admin: "అడ్మిన్ ప్యానెల్",
    logout: "లాగౌట్",
    welcome: "స్వాగతం",
    topup: "వాలెట్ రీఛార్జ్",
    postJob: "పని పోస్ట్ చేయండి",
    findWorkers: "దగ్గరలోని కార్మికులు",
    activeBookings: "యాక్టివ్ బుకింగ్‌లు",
    walletBalance: "వాలెట్ బ్యాలెన్స్",
    verifiedWorkers: "ధృవీకరించబడిన కార్మికులు",
    language: "భాష",
    otpLogin: "OTP లాగిన్",
    verifyOtp: "OTP ధృవీకరించు",
    phonePlaceholder: "10 అంకెల మొబైల్ సంఖ్య",
    otpPlaceholder: "6 అంకెల OTP (123456)",
    availableRoster: "కార్మికుల జాబితా",
    addIvrWorker: "IVR కార్మికుడిని చేర్చు",
    disputesQueue: "అడ్మిన్ రివ్యూ",
    resolveAlert: "సమస్య పరిష్కరించు",
    resetDemo: "రీసెట్ చేయి",
    radiusText: "పరిధిలో",
    searchPlaceholder: "పేరు లేదా పనిని వెతకండి...",
    allSkills: "అన్ని పనులు",
    onlineOnly: "ఆన్‌లైన్ మాత్రమే",
    allWorkers: "అందరూ కార్మికులు",
    bookEscrow: "ఎస్క్రో బుకింగ్",
    insufficientBalance: "వాలెట్ బ్యాలెన్స్ సరిపోదు! రీఛార్జ్ చేయండి.",
    ledgerTitle: "లావాదేవీల చిట్టా",
    platformCommissionText: "పని పూర్తయిన తర్వాతే 5% కమిషన్ తీసుకోబడును",
    commissionSaved: "దళారీ ఖర్చులు ఆదా"
  },
  Gujarati: {
    dashboard: "ડેશબોર્ડ",
    workers: "મજૂરો શોધો",
    jobs: "નોકરી અને બુકિંગ",
    wallet: "વૉલેટ",
    mediator: "મધ્યસ્થ રોસ્ટર",
    admin: "એડમિન કન્સોલ",
    logout: "લૉગઆઉટ",
    welcome: "સ્વાગત છે",
    topup: "વૉલેટ ટોપ અપ",
    postJob: "કામ પોસ્ટ કરો",
    findWorkers: "નજીકના મજૂરો",
    activeBookings: "સક્રિય બુકિંગ",
    walletBalance: "વૉલેટ બેલેન્સ",
    verifiedWorkers: "વેરિફાઇડ મજૂરો",
    language: "ભાષા",
    otpLogin: "ઓટીપી લોગિન",
    verifyOtp: "ઓટીપી વેરિફાય કરો",
    phonePlaceholder: "10-આંકડાનો મોબાઈલ નંબર",
    otpPlaceholder: "6-આંકડાનો ઓટીપી (123456)",
    availableRoster: "મેનેજ્ડ કામદાર યાદી",
    addIvrWorker: "IVR કામદાર ઉમેરો",
    disputesQueue: "એડમિન રિવ્યુ કતાર",
    resolveAlert: "વિવાદ ઉકેલો",
    resetDemo: "ડેમો રીસેટ",
    radiusText: "ત્રિજ્યામાં",
    searchPlaceholder: "નામ અથવા કૌશલ્ય શોધો...",
    allSkills: "બધા કૌશલ્યો",
    onlineOnly: "માત્ર ઓનલાઇન",
    allWorkers: "બધા કામદારો",
    bookEscrow: "એસ્ક્રો બુકિંગ",
    insufficientBalance: "વૉલેટ બેલેન્સ અપૂરતું છે! રિચાર્જ કરો.",
    ledgerTitle: "ટ્રાન્ઝેક્શન ખાતાવહી",
    platformCommissionText: "કામ પૂર્ણ થવા પર જ 5% કમિશન કાપવામાં આવશે",
    commissionSaved: "વચેટિયા ખર્ચની બચત"
  },
  Kannada: {
    dashboard: "ಡ್ಯಾಶ್ಬೋರ್ಡ್",
    workers: "ಕಾರ್ಮಿಕರು",
    jobs: "ಕೆಲಸಗಳು",
    wallet: "ವಾಲೆಟ್",
    mediator: "ಮಧ್ಯವರ್ತಿ ರೋಸ್ಟರ್",
    admin: "ನಿರ್ವಾಹಕ ಕನ್ಸೋಲ್",
    logout: "ಲಾಗೌಟ್",
    welcome: "ಸ್ವಾಗತ",
    topup: "ವಾಲೆಟ್ ಮರುಪೂರಣ",
    postJob: "ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ",
    findWorkers: "ಹತ್ತಿರದ ಕಾರ್ಮಿಕರು",
    activeBookings: "ಸಕ್ರಿಯ ಬುಕಿಂಗ್ಸ್",
    walletBalance: "ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್",
    verifiedWorkers: "ಪರಿಶೀಲಿಸಿದ ಕಾರ್ಮಿಕರು",
    language: "ಭಾಷೆ",
    otpLogin: "ಒಟಿಪಿ ಲಾಗಿನ್",
    verifyOtp: "ಒಟಿಪಿ ಪರಿಶೀಲಿಸಿ",
    phonePlaceholder: "10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    otpPlaceholder: "6-ಅಂಕಿಯ ಒಟಿಪಿ (123456)",
    availableRoster: "ಕಾರ್ಮಿಕರ ಪಟ್ಟಿ",
    addIvrWorker: "IVR ಕಾರ್ಮಿಕ ಸೇರಿಸಿ",
    disputesQueue: "ನಿರ್ವಾಹಕ ವಿಮರ್ಶೆ",
    resolveAlert: "ಸಮಸ್ಯೆ ಬಗೆಹರಿಸಿ",
    resetDemo: "ಡೆಮೊ ಮರುಹೊಂದಿಸಿ",
    radiusText: "ವ್ಯಾಪ್ತಿಯಲ್ಲಿ",
    searchPlaceholder: "ಹೆಸರು ಅಥವಾ ಕೌಶಲ್ಯ ಹುಡುಕಿ...",
    allSkills: "ಎಲ್ಲಾ ಕೌಶಲ್ಯಗಳು",
    onlineOnly: "ಆನ್ಲೈನ್ ಮಾತ್ರ",
    allWorkers: "ಎಲ್ಲಾ ಕಾರ್ಮಿಕರು",
    bookEscrow: "ಎಸ್ಕ್ರೋ ಬುಕಿಂಗ್",
    insufficientBalance: "ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್ ಸಾಕಾಗುತ್ತಿಲ್ಲ! ರೀಚಾರ್ಜ್ ಮಾಡಿ.",
    ledgerTitle: "ವಹಿವಾಟು ಖಾತೆ",
    platformCommissionText: "ಕೆಲಸ ಪೂರ್ಣಗೊಂಡ ನಂತರವೇ 5% ಕಮಿಷನ್ ಕಡಿತಗೊಳಿಸಲಾಗುವುದು",
    commissionSaved: "ಮಧ್ಯವರ್ತಿ ವೆಚ್ಚ ಉಳಿತಾಯ"
  }
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations["English"]) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("constructhire-lang");
    return (saved as Language) || "English";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("constructhire-lang", lang);
  };

  const t = (key: keyof typeof translations["English"]) => {
    const dict = translations[language] || translations.English;
    return dict[key] || translations.English[key] || (key as string);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
